// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frrvzeoupdkfekbymlxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZycnZ6ZW91cGRrZmVrYnltbHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MTkwMjEsImV4cCI6MjA2NzA5NTAyMX0.61SIRK7p2k2pgq4H1eKG8fMfYOLtOKBTzwx1qUlcXr4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});